# Generated by Django 4.2.6 on 2023-11-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_maincategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsilder',
            name='category',
        ),
    ]
