# Generated by Django 4.2.6 on 2023-11-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_mainsilder_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='name',
        ),
    ]
