# Generated by Django 4.2.6 on 2023-11-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_featured_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('singlenews', models.CharField(max_length=255)),
                ('dropdown', models.CharField(max_length=255)),
                ('item1', models.CharField(max_length=255)),
                ('item2', models.CharField(max_length=255)),
                ('item3', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
