# Generated by Django 4.2.6 on 2023-11-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_singlecomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarstart',
            name='singlenews',
        ),
        migrations.AddField(
            model_name='singlenews',
            name='singlenews',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
