# Generated by Django 4.2.6 on 2023-11-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_navbarstart_singlenews_singlenews_singlenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_info/')),
                ('user_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('button', models.CharField(max_length=255)),
            ],
        ),
    ]
