# Generated by Django 4.2.7 on 2023-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_posts_date_remove_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=1, upload_to='user_info/'),
            preserve_default=False,
        ),
    ]
